### ISSUE TITLE
Disconnect between project & authorized data source

### ISSUE THREAD

**Issue by danamlewis** [OpenHumans/open-humans#1012]
## Description
Member of OpenAPS Data Commons noticed that after a recent upload to the NS Data Transfer (an authorized source of the OpenAPS Data Commons) that data was not showing up in OpenAPS Data Commons. Also does not appear to be a way to pull in this data manually (maybe a future feature add). 

## Example and screenshots 
User uploads with NS Data Transfer app. 

Data shows in NS Data Transfer tool:
![image](https://user-images.githubusercontent.com/7468165/54712355-4ec78c00-4b09-11e9-94e1-8c3a061bdb7b.png)

Data also shows in OH as being on the site from the tool:
![image](https://user-images.githubusercontent.com/7468165/54712416-70c10e80-4b09-11e9-834f-4f981dccd5b5.png)

However, despite being an authorized source, data does not show in either the project page NOR does it show in the /data section:
![project page missing data](https://user-images.githubusercontent.com/7468165/54712464-9817db80-4b09-11e9-9191-9e7871a454a6.png)

![data page_NS yes](https://user-images.githubusercontent.com/7468165/54712520-b978c780-4b09-11e9-95bc-8a2a92d16025.png)
![project page_not in project](https://user-images.githubusercontent.com/7468165/54712533-c3022f80-4b09-11e9-88e3-f5c8d4e07a58.png)

Related to this possible bug, we realized that under "projects joined", this project is not showing up as a joined project:
![does not show in joined projects](https://user-images.githubusercontent.com/7468165/54712575-dca37700-4b09-11e9-8f8d-e0ae9a4cf8c6.png)

However, it does show as a 'connected project' under the profile page:
![profile page w joined projects](https://user-images.githubusercontent.com/7468165/54712616-f9d84580-4b09-11e9-9e2d-498b46d7d3a3.png)
 
## Future fixes/resolutions
This situation made me wish for a button/feature where a user could manually pull in a fresh copy of data from an authorized source. This bug came up and was recreated with two different users: one who intentionally deleted a test run of data; and one who encountered it today but isn't sure what contributed to it. In both cases, it would be ideal to pull in a fresh copy of data from a source without having to withdraw and reauthorize the project, as that creates a new memberID and is confusing for research when the data isn't reconciled as the same person. That could be a short term thing that will aid in resolving the situation; but also seems like a deeper bug causing the projects to not display/show as connected or pull in the data.

Thanks!

**Comment by jhdulaney** [comment]
Hi, there!

Just out of curiosity, when did you notice the change?  We recently (Monday) implemented pagination on some of our API endpoints.

**Comment by danamlewis** [comment]
It was flagged for me today, but might have been a problem before as well - I can't remember for sure, but I think I noticed the lack of project showing up in the 'projects joined' page before.

**Comment by jhdulaney** [comment]
Roger that.  I'll take a look at it.

**Comment by jhdulaney** [comment]
Okay, I can for sure reproduce the project not showing up in the projects joined page.

**Comment by madprime** [comment]
Hi @danamlewis - sorry for the delayed response! I've been distracted and catching up.

I think there's two issues here...

**(1) Data uploaded via "Nightscout Data Transfer" does not show up under "OpenAPS Data Commons"**

I think what's being reported is something like this:
1. *Project Foo* adds data.
2. Data is visible on the *Project Foo* page.
3. *Project Bar* requests access to data from *Project Foo*.
4. This is authorized.
5. *Project Foo* data is not visible in the *Project Bar* page.

That the behavior I expect. The "data" section in the *Project Bar* activity page (or corresponding section in the "data" page) refers to data added to the member account _by_ *Project Bar*, not data shared with it.

I wonder if there's some wording that would help here?

In the case of "OpenAPS Data Commons" there is some potential data that could be added _by_ it, described as: _"Data from any associated project research surveys (such as an engagement score or other QOL data gathered)"_ If this were added, it would show up on the [OpenAPS activity page](https://www.openhumans.org/activity/openaps-data-commons/). But data added by  [Nightscout Data Transfer](https://www.openhumans.org/activity/nightscout-data-transfer/) is expected to show up on that projects activity page, not on the activity page of projects that get access to it.

**Tagging @gedankenstuecke in case he thinks a project activity page might benefit from listing the data it has _access_ to, in addition to the data it has _added_?**

**(2) OpenAPS Data Commons is not showing up under "Projects joined"**

Pretty sure I see a bug here with the `~` on this line.

The resulting logic is incorrect: projects are listed if they meet one of the following conditions: (a) request username, (b) request "all data" (i.e. the notebooks project), or (c) do _not_ request any data sources.

**Comment by gedankenstuecke** [comment]
@danamlewis I'll close this one as @madprime has fixed the bug lined out in the second half of their comment. Regarding the display of the files: We're currently redesigning the whole activity page in any case, maybe we can discuss after that is done to see how it can be improved? 😄
