### ISSUE TITLE
Disable usersnap for mobile visitors

### ISSUE THREAD

**Issue by beaugunderson** [OpenHumans/open-humans#168]
It's not obvious what is is and I don't think there's a way to customize it.

**Comment by gedankenstuecke** [comment]
@madprime do we want to keep usersnap around at all? It seems to me that in the last two months only one person - @danamlews - reported something through it, and she has plenty of ways to get in touch with us already 😂 

For many other users it's just confusing (from my non-scientific study done by shoulder surfing ppl who encounter the website for the first time)
