### ISSUE TITLE
www.openhumans.com and www.openhumans.net have errors

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#177]
...related to SSL certificates maybe?

**Comment by BenjaminHCCarr** [comment]
`oh.net` and `oh.com` are SSL cert related; as the cert is a wildcard for *.openhumans.org. The content is mirrored correctly, I assume they are just `CNAME`.

I have to admit that holding them is fine, but I didn't even know they existed until I scrolled through early issues. I think trying to address #642 is more relevant.

SSL certs can be gotten from LetsEncrypt for the others if needed.

**Comment by BenjaminHCCarr** [comment]
Not having `heroku` stood up anywhere at the moment, I think their are two possible solutions based on the way it is deployed.

in `apache`/`nginx` speek, we don’t want to `rewrite` the domains, we want to `redirect`, which can also be done with `301`.

Two solutions that look worth exploring are:
https://stackoverflow.com/questions/5389575/heroku-how-to-redirect-http-to-http-www#5396541
https://stackoverflow.com/questions/5389575/heroku-how-to-redirect-http-to-http-www#5389654

Let me know if there is a way I can help poke on this.

**Comment by gedankenstuecke** [comment]
Yeah, I think the easiest fix for this would be do just do a permanent redirect of both the `.net` and `.com` domains to the `.org`, that way ppl will get the correct `.org` URL in their browser plus the certificate will work out.

**Comment by gedankenstuecke** [comment]
Gandi allows for easy forwarding it: https://wiki.gandi.net/en/domains/management/domain-as-website/forwarding

**Comment by madprime** [comment]
This is fixed now, with SSL in place too, for both www.openhumans.net and www.openhumans.com.

The solution involved updating to use Heroku's automatic cert generation, which is based on Let's Encrypt, and the CNAMES for www.openhumans.net and www.openhumans.com point to it.

Unfortunately, while we redirect the bare domain for HTTP connections, this doesn't fix the issue of bare domain HTTPS attempts to .org, .net, or .com variants (issue #642).
