### ISSUE TITLE
Display sharing status for data sets

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#191]
A user reported confusion regarding whether all imported data from RunKeeper had been shared with a study, when the user had only selected a subset (share "activity" but not "social"). The user saw all types listed on the Research Data page, because we import everything.

Currently the user has no way of seeing the current sharing status on data sets. A straightforward way to address this could be to list on the Research Data page what studies a given data type is shared with.

Thus, this user would see that "Activity data", and below it "Shared with: Keeping Pace". The same entry for "Social data" would not list any studies this user has shared with (because there aren't any).

**Comment by gedankenstuecke** [comment]
I'll close this for now as this will be partially solved with changes in the backend on how data sources/types are handled and that are in the making.
