### ISSUE TITLE
move AuthorizationView to a study-specific URL, throw an error if a non-study app tries to use it

### ISSUE THREAD

**Issue by beaugunderson** [OpenHumans/open-humans#305]
we want to separate these two views (one of which is presently unused, the authorization.html) so that we can simplify the logic.

**Comment by madprime** [comment]
I think this may have been somewhat related to the onsite/oauth2 distinction we now have, but not sure. It doesn't ring a bell with any current issues so I'm going to close it as obsolete/outdated. :)
