### ISSUE TITLE
Reorganization code re: activities vs studies distinction

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#483]
Reorganization or abstraction for connections: "activities" vs "studies" distinction isn't reflecting the functional differences.
General types:
API data source
Upload data source
Existing "data push" sources: PGP, GoViral, American Gut, Wild Life of Our Homes
Direct sharing
Data recipient
Could also act as a "data push": generic 'data' JSONField could have data pushed to it via API (this could trigger processing, etc).
This could happen for On-site projects too, via master code
If we think this is likely (we do) we should (right now) add this authorization by default.
As notification, not optional permission.
(We should also add badge notification.)

**Comment by gedankenstuecke** [comment]
I'll close this for now as we're getting rid of activities and studies in the sense of on-site integrated things.
