### ISSUE TITLE
Add a Public Data API token to the `User` model

### ISSUE THREAD

**Issue by beaugunderson** [OpenHumans/open-humans#552]
This token will be required to make queries to the Public Data API.

This lets us log access to the API as well as remove access to a particular token if needed.

**Comment by madprime** [comment]
This idea should be discussed! Should we require people to member accounts to get a token that lets them use the Public Data API?

Pros:
* ability to track usage of the API, which has various benefits (being able to report on use, detect/inquire about usage)
* requires users to agree to the site's terms of service, which has legal value.

Cons:
* increased friction on getting public data
* would break some current, innocuous uses of the APIs
* usage of the API may be by a project, not an individual - which isn't how we treat User accounts

**Comment by beaugunderson** [comment]
i've since used the Public Data API anonymously and appreciated that i didn't have to do anything to use it... i think that the token should not be a requirement unless there are issues with capacity, and even then it could be tiered, for example anonymous access could be rate-limited to some number of requests/minute and token access would have a higher (or no) limit.

but given that i don't think there have been any issues with capacity, this could probably be closed until such a time as there are. :)

**Comment by madprime** [comment]
I'm closing this as a "won't do it". A new issue can be opened if it becomes an idea again. :)
