### ISSUE TITLE
Integration of genevieve

### ISSUE THREAD

**Issue by BenjaminHCCarr** [OpenHumans/open-humans#559]
I am wondering if there is a timeline or milestone for adding genevieve to openhumans?

https://github.com/PersonalGenomesOrg/genevieve

It is mentioned on the https://github.com/PersonalGenomesOrg/gennotes that there is a test instance up and some screen shots?

Is there a beta.OH.org for testing? Though I guess you have enough data to break it yourselves.

**Comment by madprime** [comment]
Genevieve is currently running here: https://genevieve.herokuapp.com

The only limitation to release is an OK from the board of directors. To get that, I need to assemble materials for them to review.

To that end, I've been hoping to get legal feedback from Jen Wagner soon. She's been fairly busy, but hopefully soon!

**Comment by BenjaminHCCarr** [comment]
Good to know, thanks for providing a "test" link.
