### ISSUE TITLE
Link Members Connected Studies Badges to Projects

### ISSUE THREAD

**Issue by BenjaminHCCarr** [OpenHumans/open-humans#567]
It would be really useful if the badges on the Open Humans Profile Page shoudl link to the projects:
https://www.openhumans.org/members/
https://www.openhumans.org/member/me/
https://www.openhumans.org/member/mpball/

A lot of people will not no what the moves, fitbit, runkeeper icons, mean, and those are the obvious ones.

It would be wonderful if it linked the badges to the study info pages. It might create a few more ms of  overhead on the server, but the site is wicked quick!

Change:
`<img class="oh-badge" src="https://open-humans-production.s3.amazonaws.com/direct-sharing/badges/2/circles_badge.png" alt="Circles" title="Circles">`

To:
`<a href="https://www.openhumans.org/#activity-direct-sharing-2"><img class="oh-badge" src="https://open-humans-production.s3.amazonaws.com/direct-sharing/badges/2/circles_badge.png" alt="Circles" title="Circles">`

This doesn't quite work because of the floating bar at the top, so with a px offset it should be fine.

<a href="https://www.openhumans.org/#activity-direct-sharing-2"><img class="oh-badge" src="https://open-humans-production.s3.amazonaws.com/direct-sharing/badges/2/circles_badge.png" alt="Circles" title="Circles">

**Comment by beaugunderson** [comment]
ah, i like this idea!

**Comment by madprime** [comment]
I like this too -- I think there's a bigger/better solution needed though.

Regarding popping up under the navbar -- I believe the .anchor-tag class on a div corrects this problem.

But I think an underlying problem may we haven't created a good view for "details about a project", period. Just the activities list on the home page.

Option 1: We could add a URL that shows an information page for each project -- easy solution, easy to link? But clunky user experience for exploring project info?

Option 2: Anchor link shennanigans that jump the user to the home page, jumps to the project, and opens the project details as a pop-up. (Looks cool? Needs JS magic. Maybe annoying to not have a simple link.) c.f. https://github.com/PersonalGenomesOrg/open-humans/blob/master/static/js/lib/nav-pills.js
