### ISSUE TITLE
Endpoint to perma-reject user donated data

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#573]
For user donated data sources that have certain format expectations, we get users uploading the wrong file.

We should build endpoints for these that can be used to permanently reject and delete the original uploaded file, and send the user a notification that lets them know.

**Comment by beaugunderson** [comment]
To make this concrete: If a user uploads a VCF file for the VCFData activity it will be uploaded to S3 and then data-processing will run on that file. If it fails validation we should delete the file from S3 as part of the failure.

**Comment by madprime** [comment]
Closing this as obsolete! Since we've retired our legacy methods, what to do about files is delegated to associated projects.
