### ISSUE TITLE
Add filter/search options to members list page

### ISSUE THREAD

**Issue by abramconnelly** [OpenHumans/open-humans#581]
The page https://www.openhumans.org/members/ lists all members and can only be sorted by username.  It would be nice to be able to search for an individual member, filter by which data they've provided and order by different criteria.

**Comment by beaugunderson** [comment]
I've been working on adding this; it should be done within the next few days. :)

**Comment by beaugunderson** [comment]
This is being deployed to production now, thanks for the nudge!
