### ISSUE TITLE
Sharable data on Public Data Sharing page is outdated

### ISSUE THREAD

**Issue by Hkroog** [OpenHumans/open-humans#592]
On the Public Data Sharing page (https://www.openhumans.org/public-data/), the list of sharable data is outdated:

23andMe (genotyping data)
American Gut (gut microbiome profiling)
Fitbit (Health and activity data)
Jawbone (Health and activity data)
GoViral (viral surveillance and profiling)
Harvard PGP (whole genome data)
RunKeeper (GPS activity tracking)
Wild Life of Our Homes (environmental microbiome profiling)

**Comment by madprime** [comment]
fixed by #595
