### ISSUE TITLE
Activity Page wording tweaks

### ISSUE THREAD

**Issue by Hkroog** [OpenHumans/open-humans#593]
On https://www.openhumans.org, the first thing a person sees “Sign up, Connect Data, Join Projects”
I think it may help to keep the wording consist: 

A box that says CONNECT DATA instead of 
“Data sources” (which is what is written if someone is not logged in) 
& 
“Add data” if someone is logged in

Then a box that says JOIN PROJECTS instead of 
	“Share data”  (which is what is written if someone is not logged in) 
	&
	“New sharing” if someone is logged in

Also, regarding the line "Contribute to science! Join studies, connect data, and share" on the upper right of the Activities page, maybe 'studies' should be replaced with 'projects'.... I like the word 'studies' but some of our projects aren't studies.

**Comment by madprime** [comment]
Also, change the last box ("Connected") when logged in to say "Connected & Joined"
