### ISSUE TITLE
Main Page Tweaks

### ISSUE THREAD

**Issue by Hkroog** [OpenHumans/open-humans#604]
- Link to openhumansfoundation.org. Right now, OHF is mentioned but not linked under “About our organization” which is under “Are you a researcher?” and above “Website Policies”. Could also link to PG.org and GET here.
- Put “You decide when to share…..” before “Be a part of research….” and add the header "Your data is more powerful when you're a part of it."
- Change "Through Open Humans, you can gather valuable data about yourself and find cool projects to share it with." to "Through Open Humans, you can gather valuable data about yourself and find cool projects with which to share it. The data you provide will be private by default."

**Comment by gedankenstuecke** [comment]
This will also be done in the larger redesign efforts 👍
