### ISSUE TITLE
Ancestry DNA upload problem (from Jason)

### ISSUE THREAD

**Issue by Hkroog** [OpenHumans/open-humans#606]
From Jason: I uploaded my ancestry DNA zip file, hit "process" button, was brought to this "research-data" page. I was never given any indication that the upload process was successful, and ancestry is not one of the activities listed on my research page. It makes me think that maybe the upload failed, but i'm not sure.

**Comment by Hkroog** [comment]
https://docs.google.com/document/d/16EcAaIUHF5CtqtDQcj02-Nf0bD9KbXlJwzPmibUlZIY/edit

Word Tweaks noted here for #2 and #3 in the list of instructions

**Comment by Hkroog** [comment]
Madeleine, I emailed the updated html version to you!

**Comment by Hkroog** [comment]
From Celia on 10/7: Tried to upload Ancestry DNA but got error message "Sorry our data retrieval server seems to be down"

**Comment by madprime** [comment]
Fixed (hopefully) with this update to processing: https://github.com/OpenHumans/open-humans-data-processing/commit/f3b1456e3194f0178857514b56a3a14f458786b0
