### ISSUE TITLE
Uploaded compressed data served as uncompressed by S3

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#617]
When using the direct-sharing project API to upload a gzip-compressed file with the suffix ".json.gz" to Open Humans, the resulting file is assigned a content-type in S3 that has suboptimal results. Clicking on a link to the file results in the browser attempting to display it as text (which is gibberish), rather than simply downloading it.

**Comment by gedankenstuecke** [comment]
seems fixed 😂
