### ISSUE TITLE
Duplicate selfie data listing

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#635]
When "Data selfie" is shared publicly, it seems to be listed twice (two headings and file listings).

**Comment by beaugunderson** [comment]
looks like they should be filtered out in public_data/models.py:36 or so...

**Comment by BenjaminHCCarr** [comment]
@madprime where was it double listing? I had never noticed this, or was it internal?

**Comment by BenjaminHCCarr** [comment]
@madprime where was it double listing? I hadn't noticed it or was it internal?
