### ISSUE TITLE
multiple redirect_uris

### ISSUE THREAD

**Issue by ingrid88** [OpenHumans/open-humans#636]
Add multiple redirect_uris for OAuth2 -- the library currently used supports this IIRC (per @beaugunderson): 
* To Do: add multiple textboxes in order to add several redirect_uris

**Comment by gedankenstuecke** [comment]
@madprime After our discussion yesterday I tried the space-separated list, this does not work. :)

**Comment by beaugunderson** [comment]
@gedankenstuecke IIRC it was newline-separated i think

**Comment by beaugunderson** [comment]
actually it looks like it should work with either spaces or newlines since [it just uses `split()`](https://github.com/evonove/django-oauth-toolkit/blob/fa33444e81b3c95432999d51cdb2acdb98fc16bf/oauth2_provider/models.py#L105-L125)

**Comment by gedankenstuecke** [comment]
Ah, I see. But that doesn't really help for the initial authorization as `https://www.openhumans.org/direct-sharing/projects/oauth2/authorize/?client_id=ABCDEFGJ1234567&response_type=code` will always re-direct you back to the first URL given in there as far as I can see. And I assume there's no way to pass a redirect-uri with that?

**Comment by beaugunderson** [comment]
the way i understand it is that if you don't specify a redirect_uri in the URI you get the default, and if you do (and that URI is valid) you'll be redirected to the one specified

**Comment by gedankenstuecke** [comment]
Thanks, will have a look!

**Comment by gedankenstuecke** [comment]
Yep, that worked. I was the cause of PEBKAC. 👍
