### ISSUE TITLE
File links try to open in browser

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#637]
S3 guesses at MIME types for files, and it's not always ideal it can result in files that the browser tried to load the file (instead of download) when it's linked. This is often a bad idea: there's gibberish from compressed data and/or it's enormous. Using HTML5 it seems we could make all file links "download" type: http://www.w3schools.com/TAgs/att_a_download.asp

**Comment by BenjaminHCCarr** [comment]
Love the download code.

Also congratulations on ripping out all those tables!!!!

**Comment by madprime** [comment]
Although using the 'download' attribute seemed to work for Chrome, this attribute isn't honored for cross-origin links by some browsers, including Firefox.

[W3 spec](https://www.w3.org/TR/html5/links.html): *In cross-origin situations, the download attribute has to be combined with the Content-Disposition HTTP header, specifically with the attachment disposition type, to avoid the user being warned of possibly nefarious activity. (This is to protect users from being made to download sensitive personal or confidential information without their full understanding.)*

It does look possible to set S3 content-disposition when getting a pre-signed URL, so that might be the correct fix.
