### ISSUE TITLE
Clarify who/what an account represents in signup page

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#638]
With Nightscout we expect to see more accounts that are managed by legal guardians, that are representing data from another individual. (In this case, minors.)

We'd like to make sure these users understand how to operate these accounts: each account represents an individual. It should only be yourself, or someone you are a legal guardian for.

(Note: accounts with data from children is OK by the terms of use, provided that data isn't coming from the child directly – COPPA forbids collecting data *directly* from a child. *"If we become aware that we have directly collected personal information from a child under 13, we will delete that information."*)

**Comment by madprime** [comment]
Suggested change – in the sign up form (account creation), after *"Your imported data will be private by default."* add *"An account should represent an individual – your personal data, or someone for whom you are a legal guardian."*

Old version:
![image](https://cloud.githubusercontent.com/assets/82631/22996217/03b06c08-f39c-11e6-9fb8-e8044a3a33ee.png)

New version:
![image](https://cloud.githubusercontent.com/assets/82631/22996324/6e441574-f39c-11e6-9f8c-3f14a777240a.png)

**Comment by madprime** [comment]
Feedback invited, especially from @danamlewis!

**Comment by danamlewis** [comment]
I like! Although, I wonder about going one step further and also adding: "If you would like to upload data from multiple people (i.e. yourself and your child, or multiple children), make sure to create an account for each individual's data." 

Also, should the new sentence(s) be a line down from the privacy line? Otherwise I think eyes may skip over them.

**Comment by madprime** [comment]
I tend to avoid adding too much wording -- the failure mode is that people don't read it.

Adding a new line sounds good though! I'll try that and deploy.
