### ISSUE TITLE
About Page - rearrange text (and slight wording edit)

### ISSUE THREAD

**Issue by Hkroog** [OpenHumans/open-humans#640]
Move to top of page:

Are you a researcher **or citizen scientist**? [ADD "or citizen scientist"]
We want to help you use our platform! We have APIs and on-site tools for you to set up a study, access data, and work with Open Humans members. Everything works immediately! Read more about this in our Research Section.

The next line - Contribute to research & citizen science! - probably needs to be amended/removed so it doesn't repeat the same wordings...Maybe "Gather valuable data about yourself and share it with cool projects!" (This is basically the following line in the text.)

**Comment by gedankenstuecke** [comment]
This will also be taken care of in the larger redesign efforts! 👍
