### ISSUE TITLE
Enable project users to tag users without required data sources so they don't keep re-downloading and having to weed out people from data set

### ISSUE THREAD

**Issue by danamlewis** [OpenHumans/open-humans#644]
Current situation: Downloading data gets you all user data from a project. Some users have joined a project, but don't have the required data set for a project. 

Proposed solution: Create something on the platform to allow researcher/project admin to "filter" out or tag these people from being included in the download moving forward. Could be implemented a variety of ways.

**Comment by gedankenstuecke** [comment]
closing this as we've covered this with #690 and are working on it in `oj-proj-management`
