### ISSUE TITLE
Connecting RunKeeper asks for ability to modify RunKeeper profile

### ISSUE THREAD

**Issue by Hkroog** [OpenHumans/open-humans#645]
Support ticket #710

"I just started to connect RunKeeper and got a permissions dialog that says that Open Humans wants the ability to “access and update your profile and settings” and “access and update your friends” (emphasis mine):

I don’t mind sharing data, but I don’t want to create an access token that can modify my RunKeeper account. Is there a way it could only ask for read access instead? (Access to my profile, settings, and friends doesn’t seem to be relevant at all, at first glance.)"

**Comment by madprime** [comment]
Closing -- this isn't possible. I explained to the member that RunKeeper's API doesn't seem to have a read-only option. Not much we can do beyond promise to behave.
