### ISSUE TITLE
Like New Video on Research, sadly issues playing on Mac & Linux

### ISSUE THREAD

**Issue by BenjaminHCCarr** [OpenHumans/open-humans#654]
I like the new video on the research page:
https://www.openhumans.org/research/

I think the robot is cute and expressive, and gets across the point. I am however running into trouble playing it on both Linux and Mac even though it is bare `mp4` because of their embedding.

They are serving the naked `mp4` from https://cdn.biteable.com/9b/63/4048042/3365985_9b63b82f0d26fe630db336f677c4244eb42de77b.mp4

But they are wrapping in all kinds of tests, javascript, and analytics. The embed box has 28 trackers on it, which is likely how they monetize, which is fine, the bigger problem lies in that they restrict the ability of browsers to play the video to just to `EDGE` and `Chrome` "official".

They don't support Chromium which is what most Linux distros would be rather than chrome (I'm fine with banning IE at this point, though allowing 10 I think should have been allowed); but they outright deny Firefox altogether.

As we're serving HTML5 we can simply use the `video` tag and serve it off AWS:
```
<video width="560" height="315" controls>
  <source src="http://openhumans.org/video/HappyOpenHumansMakeTheWorldGoRound.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>
```
The video that @madprime made is 1280x720, so we might be better with `640` x ` 360` if it fits in the page just for scaling issues (x&y/2).

W3Schools has a good overview of the support and use of the `<video>...</video>` tag: https://www.w3schools.com/html/html5_video.asp

The other thing to do is drop an .htaccess file in the `video` directory:
```
RedirectMatch 301 /video(.*) https://www.openhumans.org/$1
```
Which would kick anyone trying to browse the folder back to the main page.

If we wanted to host it on AWS. It would be a hit of 4MB per view, so that might add up on the bandwidth side, but seeng as mastervarbeta is significantly bigger it may not matter.

---

Messing quite a bit with their embed script:
[view-source:https://biteable.com/watch/embed/about-open-humans-projects-1462254/9b63b82f0d26fe630db336f677c4244eb42de77b]
I don't see a way to use the CDN you paid for without allowing their browser bans and 28 analytics; as they use multiple levels of JS authentication including requiring their own linked `CSS` which does auth too.

---

It may be possible seeing as this was paid for, to toggle browser bans, off etc, on their dashboard, which would solve some of the issues.

---

The other approach would be to use the "Open Humans" YouTube account to embed it, seeing as google is already linked on the page and used for analytics this wouldn't add any privacy overhead etc:

https://www.youtube.com/user/PersonalGenomesOrg

Though we might want to think about a user name change....

**Comment by beaugunderson** [comment]
tried with Safari on macOS and it refused to play as well

**Comment by BenjaminHCCarr** [comment]
Didn't think of trying that.....

I doubt many people browse us on mobile but I bet it fails across the board....

Shoudl I fire up iceweasel, seamonkey, opera, vivaldi, and tor? 🦄

**Comment by madprime** [comment]
Sorry I'm going after the easiest option here! I've gone with a youtube embed. Hopefully this fixes the issue.

**Comment by BenjaminHCCarr** [comment]
Plays for me!!!
