### ISSUE TITLE
API docs have wrong URLs

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#661]
Some of the API docs still have the `http` URI instead of `https` (e.g. [here for single files](https://www.openhumans.org/direct-sharing/oauth2-data-upload/)). We should go through all of them and update this.

**Comment by BenjaminHCCarr** [comment]
There were only two instances outside of the two noted PDFs. OpenHumans/open-humans#664 should close this.

**Comment by madprime** [comment]
I think `http://www.openhumans.org/api/project/upload/?access_token=$TOKEN` is wrong in more than one way.

At the top of the documentation it says the endpoint is `/api/direct-sharing/project/files/upload/` (and this seems to be what I've used in python connections I've written)

**Comment by gedankenstuecke** [comment]
I think this is by now fixed in principle in #666 but even in a clean and uncached browser it seems off in at least two places (see screenshot below). If #666 has been fully deployed something might be wrong here. Otherwise it should just be deployed and then this issue can be closed. 🙂 

 
<img width="966" alt="screen shot 2017-11-19 at 17 58 33" src="https://user-images.githubusercontent.com/674899/32998871-71b82164-cd53-11e7-9a50-ce2eddad0908.png">

**Comment by madprime** [comment]
Sorry, there was a hiccup with the continuous integration setup. It's deployed now.

(Fixed by #666.)
