### ISSUE TITLE
'Data Selfie' granularity

### ISSUE THREAD

**Issue by BenjaminHCCarr** [OpenHumans/open-humans#680]
Being able to control which `data selfie` data is public and which is restricted would be a welcome addition.

I have multiple `data selfie` files, many of which I wouldn't mind sharing: including caffeine intake and sleep records, MRIs, etc; but also `data selfie` records like `XML` and other `CCR`/`CCD` formats that include things like prescription filling histories with both pharmacy, insurance, and home information, that I feel are useful for research but don't care to be public.

Changing the `data selfie` sharing option from a single "bucket" to granular "by file" system would allow greater public sharing of data on my part, and I believe others.

**Comment by gedankenstuecke** [comment]
I'm closing this here, as we have moved the data selfies into their own standalone oauth2 project. But: We have discussed changing how file sharing permissions work in a larger context and granular sharing will be part of that. But that's for a future release™. 😂
