### ISSUE TITLE
Account deletion errors

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#682]
Account deletion can fail when there are dependencies in other objects – other activities or projects the user is associated with.

See for example (authorization required) this event here:
https://sentry.io/openhumansorg/oh-production/issues/400164844/events/8837224321/

Why I think this is happening: in Django, a deletion used to trigger a cascade of deletions of related objects – this changed in 1.9, and it's likely this bug manifested at the time we upgraded to 1.9.

Cascading deletes is _not_ ideal behavior! For example, if a user that manages a project, and that project has returned data to numerous members – we do _not_ want an account deletion to trigger a cascade that destroys all of their data!

So it's maybe a good thing that there's an error – but we need to fix it, because it's also a bad error to have.

**Comment by gedankenstuecke** [comment]
Fixed by #710
