### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#693]
![image](https://user-images.githubusercontent.com/674899/34446504-5be30d20-ec90-11e7-9f43-ca67d1c9ffcd.png)

@madprime and I have been discussing some larger redesign-things in the last few weeks (see image above and [mad's tweet](https://twitter.com/madprime/status/943567343761833985).

Along with this I wanted to group some other issues that relate to the design of Open Humans:

- #641 will be solved by the redesign as envisioned so far
- The same is true for #640 and #604 
- What we hadn't discussed so far, but what should also be included is what @Hkroog mentions in #626, making it clearer for the user on whether they already joined a project.
- #625 mentions that each data source/project should come with a 'your data is private by default', that's something to keep in mind.

**Comment by madprime** [comment]
Merged an updated site to production! :tada:
