### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#699]
@madprime and I discussed that we should have some page that lists statistics about Open Humans that can give some sense of how large & active our community is (especially as our GH pages do not do justice to all the coding that individual people put into their own projects). 

A statistics page should include details on:

* Number of approved & running projects
* Maybe the number of closed projects -> sense of how many studies have already been done?
* Number of projects that are in development right now
* Number of users that joined Open Humans
* Maybe the number of total connections of member <-> projects that were created so far?

Feel free to leave comments with interesting statistics that capture community engagement that I missed so far!

**Comment by madprime** [comment]
Closed by #708

**Comment by gedankenstuecke** [comment]
Whops, thanks for closing it!
