### ISSUE TITLE
Project messages received after deauthorization

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#712]
A member reports deauthorizing a project, but then receiving a message from them – which shouldn't be possible. It sounds like a bug.

**Comment by s4y** [comment]
Member here 👋. Let me know if I can provide any more info.

**Comment by madprime** [comment]
Thanks @s4y for the bug report! (Belatedly catching up on replying.) Pretty sure this fix is good – I even added tests. ;)

**Comment by s4y** [comment]
✨\o/✨
