### ISSUE TITLE
mpball → madprime in example

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#717]
I didn't realize a username change would have this effect!

See here: https://www.openhumans.org/public-data-api/

**Comment by mcescalante** [comment]
I believe you finished this in https://github.com/OpenHumans/open-humans/commit/29302612b13b2eb8baaa2dc5c8fdf2c1eb513478 and can close this issue 👍

**Comment by madprime** [comment]
Oops, thank you!

Closed by 29302612b13b2eb8baaa2dc5c8fdf2c1eb513478 :tada:
