### ISSUE TITLE
Link to API for the connected member list from activity page

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#724]
The Public Data API has an endpoint for querying members by source. In activity pages, the section that states "Connected by N members" could be linking to this API.

An additional issue to address at the same time: this link should be using the API with a filter-by-source, which doesn't seem to be a feature it currently has.

**Comment by delenamalan** [comment]
I'm keen to work on this.

**Comment by madprime** [comment]
Hi @delenamalan! This is an issue in our main site – which is open source, but complex (it only runs in one place) and getting to the point that one can contribute to that takes quite a while. I can do this task pretty easily myself.

The best opportunities for newcomers to contribute will be with new projects (that work with this main site's APIs). :) Sometimes those needs get documented on the main site, but become modular projects in new repos – e.g. https://github.com/OpenHumans/open-humans/issues/690

(This is true for our staff hires as well. The main site is a tough place to start!)

We're working on fleshing out some documentation and suggestions for more tractable opportunities for contribution – I'm sorry it's not already available, please stay tuned in the Slack channel!

**Comment by delenamalan** [comment]
@madprime no problem. I only saw your message now so I worked on it anyway. If you don't need it, it was a fun exercise in any case. 😸

**Comment by madprime** [comment]
@delenamalan oh gosh, wow! And I was so worried about someone getting lost in our main site. :D You rock. I might not have time to review this until tonight – thank you!

**Comment by gedankenstuecke** [comment]
I assume this can be closed thanks to #725?

**Comment by madprime** [comment]
Yup! closed by #725 – thank you @delenamalan!
