### ISSUE TITLE
Stats of project is inaccurate; enable project admins to remove non-participants (Technical and Organizational issue)

### ISSUE THREAD

**Issue by danamlewis** [OpenHumans/open-humans#737]
**Issue:** the "stats" of a project reflects the number of people who click "join" on a project, even if they're not legitimate/valid participants (e.g. don't have required data sources). 

Related to the project admin tools that need to be built (https://github.com/OpenHumans/open-humans/issues/690), we need to decide:
- If project admins can 'remove' participants
- Do 'removed' participants get notified? Should they?

#### Example

![screen shot 2018-03-07 at 3 06 48 pm](https://user-images.githubusercontent.com/7468165/37123645-d676f3bc-2219-11e8-9c05-4fbba5ff2fc2.png)

People cite this as "95 OpenAPS users have donated data". This is incorrect. This number is inclusive 50-75% which are OH accounts that have "joined" the project despite not having OpenAPS data, and I would like a way to remove non-valid data sets and associated accounts so this number is an accurate reflection of this data commons.

**Comment by mcescalante** [comment]
@akshitac8 we have been recommending that Outreachy participants start with something other than the main open humans repository, due to moving parts. You can see on our [Outreachy ideas page](http://openhumansfoundation.org/outreachy/ideas/) a few of those repos. Feel free to chat with us in Slack about specific issues or anything else! 😄

**Comment by danamlewis** [comment]
Nudging on this - since the project admin dashboard is currently being developed (hooray!), I'd like to also see this issue (inaccurate count of project participants) addressed in tandem.

* One solution would be to allow a UserGroup (defined by Admin in the dashboard) to replace the 'join' count. 
* Another option might be removing users via the API. 

^ Likely needs a wider OH community discussion, so wanted to re-raise this.

**Comment by madprime** [comment]
Raising this issue to attention as part of our updates towards GDPR compliance.

I think the member will _not_ be notified with this feature.

I think a project should have the ability to do this, but not be required to do it. And this ability exists, via the messaging feature. So, taking a minimalist approach here, and sticking to plain removal – just as if a member withdraws/deauthorizes a project themselves on the site.

It should be implemented as an API endpoint, as well as on-site.

**Comment by danamlewis** [comment]
@madprime what about the wiki? https://github.com/OpenHumans/open-humans/wiki
