### ISSUE TITLE
setting Oauth2 project to inactive doesn't disable signup

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#796]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description
On the project management/update page the description for `Active` is the following: 

> "Active" status is required to perform authorization processes, including during drafting stage. If a project is not active, it won't show up in listings of activities that can be joined by participants, and new data sharing authorizations cannot occur. Projects which are "active" but not approved may have some information shared in an "In Development" section, so Open Humans members can see potential upcoming studies. Removing "active" status from a project will not remove any uploaded files from a project member's profile.

but I found that setting an oauth2 project to `Active == False` on the project management page doesn't actually inhibit people from still joining it.

## Example

The `opensnp` activity is currently set to `inactive` but people can still join.

**Comment by jhdulaney** [comment]
Fixed #917
