### ISSUE TITLE
Public data activity is broken

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#798]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description
the public sharing feature seems to be broken right now, e.g. if you go to https://www.openhumans.org/member/me/joined/ and are joined in the public data sharing study the link leads to https://www.openhumans.org/activity/None/

**Comment by gedankenstuecke** [comment]
The link should instead point to https://www.openhumans.org/public-data/ (as @madprime pointed out earlier today on a call)

**Comment by BenjaminHCCarr** [comment]
Okay, so this is returning `None` due to an empty field in `Public Data Sharing`

This is the relevant template location: https://github.com/OpenHumans/open-humans/blob/master/private_sharing/templates/private_sharing/project-detail.html#L97-L106

**Comment by BenjaminHCCarr** [comment]
Working on fixing the `URL` in https://github.com/OpenHumans/open-humans/blob/master/public_data/urls.py

**Comment by BenjaminHCCarr** [comment]
was wrong about the location of the incorrect `url`: https://github.com/OpenHumans/open-humans/blob/master/open_humans/templates/member/my-member-joined.html#L24

```
{% for activity in activities %}
    {% if activity.is_connected and activity.share_data and activity.active %}
    <li>
      <p>
        <b><a href="{% url 'activity-management' activity.url_slug %}">{{ activity.verbose_name }}</a></b><br>
        {{ activity.description }}
      </p>
    </li>
    {% endif %}
  {% endfor %}
```
