### ISSUE TITLE
Better handling of 404s

### ISSUE THREAD

**Issue by jhdulaney** [OpenHumans/open-humans#830]
## General Checkups
- [*] Have you checked that there isn't already an existing issue that describes what you report below?
- [*] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description
Whenever we hit a missing resource, django throws an internal server error page up (or, if debuging is enabled, a backtrace).  Better would be to display an actual 404 page.

## Related Issue(s)
The new Boto upgrade no longer fails silently on s3 resources not being found.  This exacerbates the existing 404 problem.

## Example
During my S3 bucket testing, I switched buckets but neglected to switch databases.  This caused me to hit missing objects.

**Comment by madprime** [comment]
Ouch, this sounds like bad behavior. But it's also unclear to me when it's occurring & the past behavior vs. current vs. proposed... I think a "silent failure" with a broken image (for example) on a template is probably preferred in a lot of cases?
