### ISSUE TITLE
Members list error when filtering on activity

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#857]
## Description
The members page offers a dropdown for filtering the list according to activity. This seems to be broken now.

1. selecting "23andme Upload" in https://www.openhumans.org/members/
2. results in this URL (which has an error): https://www.openhumans.org/members/?filter=direct-sharing-128
3. Sentry report: 
```
FieldError: Cannot resolve keyword 'badges' into field.
...
File "open_humans/member_views.py", line 91, in get_queryset
    badges__contains=[{'label': filter_name}])
```

## Related Issue(s)
#846

**Comment by jhdulaney** [comment]
Fixed #860
