### ISSUE TITLE
Social login.

### ISSUE THREAD

**Issue by jhdulaney** [OpenHumans/open-humans#863]
One of the big items on our usability improvements list is making it easier to create accounts and login with them.

To that end, we'd like to add the ability to create accounts and login using external identity provider services.

Currently, there are a couple of possibilities.

python-social-auth

python-social-auth (after a series of name changes was originally known as djang-social-auth)

Pros:
Already semi-integrated into the site

Cons:
Ugly code
Not very flexible
Last commit from May

django-allauth

Pros:
All in one auth solution
Active development
flexible (for example, for account creation we can range from zero questions when using an external identity provider to however many we want)

Cons:
Have to remove existing auth framework and provide a way to migrate over to the new method

Roll our own:

Pros:
Can get precisely what we want

Cons:
Still would have to remove or modify existing code
huge project
Future maintainability may be difficult

**Comment by madprime** [comment]
:+1: I think that's best too. I guess the next bit of work may be to figure out these?
1. how hard is it to switch from django-user-accounts to django-allauth?
2. is it necessary or worth doing?

**Comment by jhdulaney** [comment]
I think that it would be the correct thing to do to full switch to django-allauth.  I am currently unsure of the difficulty, though I think that it would mostly lay in maintaining a smooth migration.

I believe that I would like to proceed as follows:

Remove the existing python-social-auth code.  I would even go as far as to say that I would like this to be merged into master prior to proceeding.

Replace django-user-accounts with django-allauth

Impliment social login (which, at this point, should be trivial)

Once again, I'd like to do these as discrete steps, fully merged into master (and probably in prod) before proceeding.  I feel like this would minimize unexpected Gotchas.

**Comment by madprime** [comment]
All three steps sound good to me! Let's go ahead and make an issue for each of those - I'll let you do the honors, since you made the plan. :)

**Comment by jhdulaney** [comment]
Okay, now that's done.

I guess that we should decide on which login providers we would like to support.

Would it be better to whitelist or blacklist?

Full listing provided by allauth is here:
https://django-allauth.readthedocs.io/en/latest/installation.html

I think that we should whitelist.  Get the major players (FB, Googles, Twitter, Github), plus I'd suggest Gitlab, openid, persona, dropbox, baidu, bitbucket (both), and cern.

**Comment by jhdulaney** [comment]
Oh, and, maybe reddit?
