### ISSUE TITLE
Can't hide membership for projects that aren't data sources

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#866]
It seems that I'm unable to hide project membership for any activities that aren't acting as data sources, the button isn't there.

e.g. screenshot below from [Genevieve Genome Report](https://www.openhumans.org/activity/genevieve-genome-report/)

---

![image](https://user-images.githubusercontent.com/82631/45569104-639e2c80-b813-11e8-9a20-6869939ffc8f.png)

**Comment by jhdulaney** [comment]
Fixed #869
