### ISSUE TITLE
Public API "members by source" behaves weirdly on filter

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#867]
## Description
A filter applied to the "members by source" public API endpoint is behaving weirdly.

You can find examples of this behavior by looking at activity. There's a link related to the number of members that have connected the project, "Connected by X members".

## Example
For example, [23andMe Upload](https://www.openhumans.org/activity/23andme-upload/) currently says "Connected by 1024 members."

Clicking this link goes here: https://www.openhumans.org/api/public-data/members-by-source/?source=direct-sharing-128

Which produces something like this:

```
{
    "count": 27,
    "next": null,
    "previous": null,
    "results": [
        {},
        {},
        {},
        {
            "source": "direct-sharing-128",
            "name": "23andMe Upload",
            "usernames": [
                "member1",
                "member2",
                "member3",
                "member4",
                ...
                "member1022",
                "member1023",
                "member1024"
        },
        {},
        {},
        {}
    ]
}
```

I'm not sure what it used to do before recent updates, but it should probably not return a list of `{}` for all the projects that were filtered out?

**Comment by jhdulaney** [comment]
Fixed #869
