### ISSUE TITLE
Members list displays badges for deauthed/withdrawn projects

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#868]
## Description
In the members list, currently members have badges shown for projects they have withdrawn/deauthorized.

The culprit is probably this line, which doesn't filter on authorized?
https://github.com/OpenHumans/open-humans/blob/master/open_humans/templatetags/utilities.py#L314

## Example
The listing for me below is showing me as a member of Nightscout and OpenAPS projects, which I joined at some point for testing purposed, but withdrew/deauthorized.

-----

![image](https://user-images.githubusercontent.com/82631/45571668-d3b0b080-b81b-11e8-990b-04b1a923d1cd.png)

**Comment by jhdulaney** [comment]
Fixed #869
