### ISSUE TITLE
Public Data API Server Error

### ISSUE THREAD

**Issue by dnvrdave** [OpenHumans/open-humans#875]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description

I get an error on the Public Data API when clicking this link:
“There are also two ways to see which users have which data sources:”
https://www.openhumans.org/api/public-data/sources-by-member/

## Example

This message pops up and it logs me out:
Server error
Sorry, your request resulted in a server error. The error has been logged and we'll investigate it.

**Comment by madprime** [comment]
Fixed by #876 - thanks @dnvrdave & @jhdulaney !
