### ISSUE TITLE
Checkbox during authorization doesn't hide membership

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#897]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description
When joining and authorizing a project, on that authorization form:

(a) the checkbox seems to not be working to hide membership visibility
(b) the language on this form is confusing - it should be shorter and more clear what the checkbox does.

## Example
During a test of connecting the AncestryDNA app, I marked the checkbox for hiding visibility. The result was that I did _not_ have hidden visibility for the project. The activity page states my membership is visible.

**Comment by jhdulaney** [comment]
Seems to be just broken for oauth2 apps.
