### ISSUE TITLE
Link Member Withdrawal page

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#911]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description
The member withdrawal page that project leads can use to see which members have left the project and which request data deletion is found at `/direct-sharing/projects/withdrawn-members/my-test-on-site-project-name/` but it is not linked anywhere. 

The only way to find this page is by receiving an email on withdrawal, but right now getting these emails is optional. The withdrawal page needs to be linked to from the Project management interface on the main site.

This affects both project leads as they never get the information they want and it also affects project members for whom data might not be deleted as project leads never get the message.

**Comment by jhdulaney** [comment]
Fixed #915
