### ISSUE TITLE
Exchange member endpoint is slow

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#918]
## Description
The API endpoint for a project getting member-specific information is very slow. This is leading to Heroku alerts about long responses.

The URL for the endpoint is `/api/direct-sharing/project/exchange-member/`.

## Example
The following situation reproduces a long response...

* Running the site locally
* Using read-only access to the production database
* Using `requests` to call this endpoint with an access token corresponding to the in-development `PersonalDataAPI` project (project id: 187) and member `madprime`

**Comment by gedankenstuecke** [comment]
This was uncovered through the `Overland` project which (accidentally) amassed 300+ small files for some members. 

With so many files the bottleneck probably is the S3 signing of download links returned when doing the `exchange-member`. In the most extreme case observed this leads to a page load time of >30 seconds, which in turn is terminated by Heroku.

**Comment by gedankenstuecke** [comment]
Added the `affects-users` label as users will be unable to load the activity page in such cases as well due to the heroku timeout.

**Comment by madprime** [comment]
In addition to the API endpoint, activity pages with premade S3 links are also failing when there's too many files. We think we should extend the public file URL method to work for private files, using some sort of token authorization. This URL then redirects to an S3 link generated on the fly, one file at a time.

**Comment by jhdulaney** [comment]
Closed via #935 and #937
