### ISSUE TITLE
Changes needed for redesigned activity pages

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#926]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description

We started drafting a re-design of the [activity pages](https://balsamiq.cloud/shqwfbq/p4e1tmg/r28A0) to make them more interactive, having clearer calls to action as well as improved usability when it comes to managing a member's options in managing their membership in a project. 

To realize those things we need to have some changes done on the backend: 

- Message permissions for members should always be granted instead of being optional. For this we need to remove this option from the project management pages and check whether all current projects have enabled this
- Add a field to the ProjectMember model that stores when a member last joined a given project
- The OAuth2 Project model needs to be extended to store an additional URL for the privacy policy/terms of use, as we want to link out to these from the new activity pages
- The Personal Data Exploratory needs an API endpoint that allows fetching a list of notebooks that use a given data source.

**Comment by gedankenstuecke** [comment]
The Exploratory endpoint has been implemented in OpenHumans/jupyter-gallery#49 and is already deployed!

**Comment by jhdulaney** [comment]
These tasks are completed.
