### ISSUE TITLE
Signing up an open humans account going through an oauth2 project skips email verification requirements

### ISSUE THREAD

**Issue by jhdulaney** [OpenHumans/open-humans#927]
## General Checkups
- [*] Have you checked that there isn't already an existing issue that describes what you report below?
- [*] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description
You can sign up for an oauth2 project without confirming email
so, in oauth2 project, click get started/login
create an account
fill out and submit form
It takes you to the project authorization page
you authorize
you're now part of the project
No email confirmation necessary

This seems less than ideal.  While it would be relatively straightforward to store the redirect in the same manor as the reset password code does, preventing a user from immediately authorizing a project until they validate their email does introduce quite a lot of friction.  This is going to require some design thinking to resolve.

## Related Issue(s)
#28

**Comment by madprime** [comment]
Closing this as obsolete. We no longer enforce email verification. Previously we tried to do so, but it was haphazard (as noted in this issue).

Now, we're presenting an omnipresent message to the unverified user that says: "Please [verify your email address]()! As good stewards of your data, we want to be able to contact you."
