### ISSUE TITLE
Field to disallow public data for a project data source

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#932]
We'd like to add a boolean field to the project model that is admin-facing, called something like `no_public_data`. When set to `True` data from this project can't be made public by members.

The need for this feature follows from the project approval discussion for a Google Search History data source. Due to the sensitive nature of this data, the community approval decision was to "approve" only if public data sharing is blocked for the project data. https://discourse.openhumans.org/t/approval-for-google-search-history-analyzer/48/27

As part of this feature, code updates should result in the following:
* a boolean field is added to project models (only adjustable by site admins)
* when `True` this should prevent data from that project being publicly shared

**Comment by jhdulaney** [comment]
Should be visible on the admin page only

**Comment by jhdulaney** [comment]
Merged #950
