### ISSUE TITLE
Improve main page load time

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#942]
The main page (`/`) in production seems to have slow load times, with a median around 1.2 to 1.3 seconds.

**Comment by jhdulaney** [comment]
Tried a couple of different page speed analyzers, and our biggest issue is images.  Image load times seem to range from 1 to 4 seconds.

**Comment by jhdulaney** [comment]
Also, Google recommends sending js in smaller payloads.

**Comment by jhdulaney** [comment]
Fixed #946.
