### ISSUE TITLE
Member images aren't loading on the "Member list" page

### ISSUE THREAD

**Issue by beaugunderson** [OpenHumans/open-humans#972]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description

The "Member list" page is not loading member images:

![https://i.imgur.com/wY8Ej5t.png](https://i.imgur.com/wY8Ej5t.png)

**Comment by beaugunderson** [comment]
I see the image URL gives an "access denied" error:

[https://open-humans-production.s3.amazonaws.com/member/mpball/profile-images/portrait_20140925.png](https://open-humans-production.s3.amazonaws.com/member/mpball/profile-images/portrait_20140925.png)

I seem to recall that we used a thumbnail manager with its own set of template tags to manage these images, but that seems to be a direct URL...

**Comment by beaugunderson** [comment]
Ah, yes, I think that's the issue. In `member-detail-content.html`:

```
    {% if member.profile_image %}
    {% thumbnail member.profile_image '250x250' as image %}
      <img class="img-rounded img-responsive profile-image"
        src="{{ image.url }}">
    {% endthumbnail %}
    {% endif %}
```

vs. `member-list.html`:

```
        {% if member.profile_image %}
            <img class="img-circle member-profile-img" src="{{ member.profile_image.url }}"
              alt="The Member's profile image.">
        {% else %}
          <img class="img-circle" style="width: 30px; height: 30px;"
            src="{% static 'images/profile-placeholder.png' %}"
            alt="A placeholder image for a user without a profile image.">
        {% endif %}
```

**Comment by jhdulaney** [comment]
That's weird, some of them are.

I removed the thumbnailer because it was adding a significant amount of processing time, causing the page to take a very long time to render, and occaisionally time out.

**Comment by beaugunderson** [comment]
Whether they load or not may depend on when the user uploaded their profile image, if the S3 permissions were updated to be non-public by default (or vice versa, if old ones work and new ones don't work).

**Comment by beaugunderson** [comment]
You could use the thumbnailer again if you added a scheduled task in Heroku to ensure the cache was always warm... (The improvement there would be the smaller amount of network data sent on page load, since the member list page is displaying the full-size image now)

**Comment by jhdulaney** [comment]
Fixed.
