### ISSUE TITLE
Form for creating OAuth2 projects generates on-site projects

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#988]
## General Checkups
- [x] Have you checked that there isn't already an existing issue that describes what you report below?
- [x] Have you checked that there isn't already an open pull requests for this issue/update/change?

## Description

When creating a new Oauth2 project the submitted form will not create an oauth2 project, but rather an on-site project, which means that right now it's impossible to create new OAuth2 projects!

## Example

Tried to create a new Oauth2 project just now and observed that behaviour. @madprime reproduced with a local dev instance.

**Comment by madprime** [comment]
Looks like it's from this:
https://github.com/OpenHumans/open-humans/commit/a0f50eee4bdba869cb455c71ea0d2136cc9ace88#diff-db6f663aaaf813cbe45099b04bb7e3f7R354

I'd like to be the one to fix this, but I'd like to hear from @jhdulaney the rationale for replacing the default behaviors of `CreateView` and `UpdateView` that these were using before... thanks!

**Comment by madprime** [comment]
(followup: looks like it's a mistake, leftover code from an abandoned approach - I'll be reverting to the standard approach)
